name: Deploy Website (dev)

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

permissions:
  contents: read

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      ref: ${{ github.event.workflow_run.head_sha }}
    secrets: inherit
